
import "./global.css"; 
export const metadata = {
  title: "Scheduler",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <html lang="en">
        <body>
          
                {children}
              
        </body>
      </html>
    
  );
}
